// قائمة Hippodromes France officiel — LeTrot + France Galop
// مرتبة، مع.code ديال PMU
const FRANCE = [
  // ============ LE TROT (ATTELE / MONTE / HAIE) ============
  'VINCENNES', 'CAGNES/MER', 'CAGNES SUR MER', 'CABOURG', 'VICHY', 'ENGHIEN',
  'ENGHIEN SOISY', 'LA CAPELLE', 'LE CROISE LAROCHE', 'LE CROISE LAROCHE',
  'SAINT CYR', 'BORDEAUX LE BOUSCAT', 'LAVAL', 'AMIENS', 'ENGHIEN SOISY',
  'LA ROCHE SUR YON', 'SAINT GEORGES', 'AGON', 'CHATELAY', 'GOURNAY EN COTENTIN',
  'LE MANS', 'NORT', 'VIRE', 'LE COUDRAY', 'CHANTILLY', 'COMPIEGNE',
  'CAEN', 'CABOURG', 'ROUEN', 'DIEPPE', 'LE HAVRE', 'ARGENTAN',
  'ANGERS', 'CHOISY LE ROI', 'NANTES', 'SAINT BRIEUC', 'PONT DE VIVAUX',
  'ARGENTAN', 'EVREUX', 'GRAIGNES', 'CHATEAUBRIANT', 'LE LION D AN GERS',
  'LE LION D ANGERS', 'SAINT CLOUD', 'LONGCHAMP', 'CHANTILLY', 'DEAUVILLE',
  'PARISLONGCHAMP', 'FONTAINEBLEAU', 'MANTES', 'SAINT MALO', 'LA ROCHEFORT',
  'LA CAPELLE', 'MARONAS', 'SALTO', 'SAINT POL', 'ARGENTAN',
  'HONY', 'GRAIGNES', 'BERNAY', 'FORMES', 'LE MANS', 'SOURS',
  // additions
  'LYON LA SOIE', 'LYON PARILLY', 'SAINT GEORGES', 'ROBERVAL', 'LE CHATEAUROUX',
  'CHATILLON', 'VICHY', 'MOULINS', 'LAVAL', 'PONTCHATEAU', 'SAINT GALMIER',
  'BORDEAUX LE BOUSCAT', 'CAGEN SUD', 'AGEN LA GARENNE', 'AGEN', 'CAEN',
  'STRASBOURG', 'REIMS', 'HYERES', 'LES SABLES D OLONNE', 'LA CAPELLE',
  'PORNICHET', 'MAUQUENCHY', 'MARSEILLE VIVAUX', 'MARSEILLE BORELY',
  'CARRERE', 'ABY', 'BERGEN', 'AMAL', 'STOCKHOLM', 'ROMANDE', 'BERGEN',
];

// set binaire
const SET = new Set(FRANCE.map(s => s.toUpperCase()));

function isFrance(hip) {
  const k = String(hip || '').toUpperCase().trim();
  if (SET.has(k)) return true;
  // لا شيء
  return false;
}

export { FRANCE, SET, isFrance };
